/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class helloj_HelloLib */

#ifndef _Included_helloj_HelloLib
#define _Included_helloj_HelloLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helloj_HelloLib
 * Method:    hi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_helloj_HelloLib_hi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
