ARG FROM_IMAGE

FROM ${FROM_IMAGE}

ARG USERID
ARG USERNAME

RUN groupadd -g ${USERID} ${USERNAME}
RUN useradd -m -l -u ${USERID} -g ${USERNAME} ${USERNAME}
USER ${USERNAME}

# use cached .m2
RUN ln -s /project/.temp-m2 ~/.m2
# use cached .ivy2
RUN ln -s /project/.temp-ivy2 ~/.ivy2