ARG FROM_IMAGE

FROM ${FROM_IMAGE}

ARG USERID
ARG USERNAME

# alpine already comes with libz, libbz2

RUN adduser -D -u ${USERID} ${USERNAME}
USER ${USERNAME}

# use cached .m2
RUN ln -s /project/.temp-m2 ~/.m2
# use cached .ivy2
RUN ln -s /project/.temp-ivy2 ~/.ivy2